### ISSUE TITLE
Scraper Assumes Site is SSL

### ISSUE THREAD

**Issue by Brycey92** [Kas-tle/EnjinScraper#15]
On first and subsequent runs, after following Windows instructions in the README, the following is output (minus the session ID after first run):
```
[i] Starting enjin-scraper v1.0.0...
[+] Authenticated with session ID [REDACTED]
G:\Enjin Website Download\EnjinScraper\src\scrapers\authenticate.ts:28
}
                                                         ^
TypeError: Cannot read properties of undefined (reading 'find')
    at G:\Enjin Website Download\EnjinScraper\src\scrapers\authenticate.ts:50:64
    at Generator.next (<anonymous>)
    at fulfilled (G:\Enjin Website Download\EnjinScraper\src\scrapers\authenticate.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Kas-tle** [comment]
I've now published this as an NPM package. Please see the updated installation instructions.

Also ensure you are using the correct domain (e.g. if it includes a www, you must include it).

**Comment by Brycey92** [comment]
I switched to using the npx package. Accessing my site from [galaxy-craft.com](https://galaxy-craft.com) just redirects to [www.galaxy-craft.com](https://www.galaxy-craft.com). Removing the `www` from the `domain` in my config gives an ETIMEDOUT error, which I've truncated and pasted below. Leaving the `domain` as `"www.galaxy-craft.com"` still gives the error above.
```
[i] Starting enjin-scraper v1.0.0...
[ERROR] Error making get request 0000001: connect ETIMEDOUT 18.209.54.50:443
Error: connect ETIMEDOUT 18.209.54.50:443
    at AxiosError.from (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\axios\dist\node\axios.cjs:825:14)
    at RedirectableRequest.handleRequestError (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\axios\dist\node\axios.cjs:2971:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
AxiosError: connect ETIMEDOUT 18.209.54.50:443
    at AxiosError.from (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\axios\dist\node\axios.cjs:825:14)
    at RedirectableRequest.handleRequestError (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\axios\dist\node\axios.cjs:2971:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by Kas-tle** [comment]
Oh I think I see what's going on here... your site does not have SSL...

**Comment by Brycey92** [comment]
Yeahhhh... Enjin broke that a long time ago and hasn't answered tickets for years 😭

**Comment by Kas-tle** [comment]
Hmm unfortunately I only pushed my changes to the npm package last night rather than to the repo. So I will not be able to address this til I get home. But I will add a config option to disable SSL for you.

**Comment by Brycey92** [comment]
Thank you! :smile:

**Comment by Kas-tle** [comment]
Your site seems to have SSL enabled now. Would you still like me to update this? Have you been able to use the scraper since?

**Comment by Kas-tle** [comment]
https://github.com/Kas-tle/EnjinScraper/commit/f98e3c0eba72eefb4d593588ace48dbf0d5a4d20

**Comment by Brycey92** [comment]
Thanks for implementing this! Oddly, it looks like you're right; Enjin appears to have fixed my site's SSL with 9 days to go before they shut it down, which is a head-scratcher for sure...

In any case, it seems to work now without needing the `disableSSL` option! Aside from https://github.com/Kas-tle/EnjinScraper/issues/16 that is. Hopefully this is an easier fix, as I already owe you a beer or 6 so far :joy:

I saw [your reply](https://www.enjin.com/forums/page/19/m/10826/viewthread/33743439-announcing-retirement-enjin-website-builder/post/140216388#p140216388) to my forum thread post, and ended up manually saving the DonationCraft data.

You may want to tell the thread about your new ability to scrape non-SSL websites, as it will be very useful to anyone whose SSL is still not working!
