### ISSUE TITLE
Gallery scraping issues

### ISSUE THREAD

**Issue by Brycey92** [Kas-tle/EnjinScraper#16]
After completing forum scraping, gallery scraping almost immediately fails. Oddly, when I moved the contents of the `target` folder out and retried, I got a different stack trace when scraping galleries.

```
[i] Scraping galleries...
[•] Getting albums for preset 30503267 [(1/1)]
[ERROR] Error getting album 236003: You do not have access to this gallery.
[•] Getting images for album 236004 (2/4) [(1/1)]
Inserted 236004 into table 'gallery_albums'
Inserted 5 rows into table 'gallery_images'
G:\Enjin Website Download\EnjinScraper\src\util\database.ts:4
import { TableSchema } from '../interfaces/tableschema';
           ^
TypeError: Cannot read properties of undefined (reading 'length')
    at G:\Enjin Website Download\EnjinScraper\src\util\database.ts:131:42
    at new Promise (<anonymous>)
    at G:\Enjin Website Download\EnjinScraper\src\util\database.ts:130:12
    at Generator.next (<anonymous>)
    at G:\Enjin Website Download\EnjinScraper\src\util\database.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (G:\Enjin Website Download\EnjinScraper\src\util\database.ts:4:12)
    at insertRows (G:\Enjin Website Download\EnjinScraper\src\util\database.ts:153:12)
    at G:\Enjin Website Download\EnjinScraper\src\scrapers\galleries.ts:87:29
    at Generator.next (<anonymous>)
```

```
[i] Scraping galleries...
[•] Getting albums for preset 30503267 [(1/1)]
[ERROR] Error getting album 236003: You do not have access to this gallery.
[•] Getting images for album 236004 (2/4) [(1/1)]
Inserted 236004 into table 'gallery_albums'
Inserted 5 rows into table 'gallery_images'
C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\enjinscraper\dist\src\util\database.js:155
            const values = new Array(rows[0].length).fill('?').join(', ');
                                             ^

TypeError: Cannot read properties of undefined (reading 'length')
    at C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\enjinscraper\dist\src\util\database.js:155:46
    at new Promise (<anonymous>)
    at C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\enjinscraper\dist\src\util\database.js:154:16
    at Generator.next (<anonymous>)
    at C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\enjinscraper\dist\src\util\database.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\enjinscraper\dist\src\util\database.js:4:12)
    at insertRows (C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\enjinscraper\dist\src\util\database.js:153:12)
    at C:\Users\Bryce\AppData\Local\npm-cache\_npx\83b135d599749a5b\node_modules\enjinscraper\dist\src\scrapers\galleries.js:88:49
    at Generator.next (<anonymous>)

Node.js v19.9.0
```

**Comment by Kas-tle** [comment]
So it looks like the issue is probably it trying to insert into the tags table but insertRows fails if there are no tags.. insertRows should probably have a check to immediately resolve the promise if the passed arrays are empty

**Comment by Kas-tle** [comment]
Feel free to PR if you understand that, otherwise I will address tomorrow

**Comment by Brycey92** [comment]
The new PR is tested and working, thanks for the direction!

Also, this confirms your suspicions about the gallery tags.
```
[i] Scraping galleries...
[•] Getting albums for preset 30503267 [(1/1)]
[ERROR] Error getting album 236003: You do not have access to this gallery.
[•] Getting images for album 236004 (2/4) [(1/1)]
Inserted 236004 into table 'gallery_albums'
Inserted 5 rows into table 'gallery_images'
Ignoring insertion of 0 rows into table 'gallery_tags'
[•] Getting images for album 236005 (3/4) [(1/1)]
Inserted 236005 into table 'gallery_albums'
Inserted 4 rows into table 'gallery_images'
Ignoring insertion of 0 rows into table 'gallery_tags'
[ERROR] Error getting album 236006: You do not have access to this gallery.
Inserted galleries into table 'scrapers'
[+] Finished gallery scraping
```

I still can't figure out why I wouldn't have access to my own galleries as site owner, though.
